swagger: "2.0"
info:
  title: proto/schema/tags/tags.proto
  version: version not set
tags:
  - name: TagsService
  - name: TokenService
  - name: DiscordService
  - name: SignUpService
  - name: DiscordCallbackService
  - name: UserService
  - name: MeService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/auth/discord:
    post:
      operationId: DiscordService_GetDiscord
      responses:
        "200":
          description: A successful response.
          schema:
            type: string
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      tags:
        - DiscordService
  /v1/auth/discord/callback:
    get:
      operationId: DiscordCallbackService_GetDiscordCallback
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/resourcesDiscordToken'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: code
          in: query
          required: false
          type: string
      tags:
        - DiscordCallbackService
  /v1/auth/sign_up:
    post:
      operationId: SignUpService_PostSignUp
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/resourcesAccount'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: name
          in: query
          required: false
          type: string
        - name: email
          in: query
          required: false
          type: string
        - name: password
          in: query
          required: false
          type: string
        - name: display_name
          in: query
          required: false
          type: string
        - name: avatar_url
          in: query
          required: false
          type: string
      tags:
        - SignUpService
  /v1/auth/token:
    post:
      operationId: TokenService_PostToken
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/rpcPostTokenResponse'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: refresh_token
          in: query
          required: false
          type: string
      tags:
        - TokenService
  /v1/tags:
    get:
      operationId: TagsService_GetTags
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/rpcGetTagsResponse'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
        - name: smallest_tag_id
          in: query
          required: false
          type: string
        - name: biggest_tag_id
          in: query
          required: false
          type: string
        - name: w
          in: query
          required: false
          type: string
      tags:
        - TagsService
  /v1/users/@me:
    get:
      operationId: MeService_GetMe
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/resourcesAccount'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      tags:
        - MeService
    put:
      operationId: MeService_PutMe
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/resourcesAccount'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/rpcAccountPatcher'
      tags:
        - MeService
  /v1/users/{user_id}:
    get:
      operationId: UserService_GetUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/resourcesAccount'
        "422":
          description: Validation Error
          schema: {}
          examples:
            application/json:
              detail:
                - loc:
                    - string
                    - 0
                  msg: string
                  type: string
      parameters:
        - name: user_id
          description: Path parameter representing the user's ID
          in: path
          required: true
          type: string
      tags:
        - UserService
definitions:
  resourcesAccount:
    type: object
    example:
      avatar_url: https://example.com/
      created_at: "2024-01-11T07:56:02.206Z"
      display_name: string
      github_id: string
      id: string
      name: string
      profile: string
      twitter_id: string
      updated_at: "2024-01-11T07:56:02.206Z"
    properties:
      id:
        type: string
      name:
        type: string
      display_name:
        type: string
      avatar_url:
        type: string
      profile:
        type: string
      twitter_id:
        type: string
      github_id:
        type: string
      created_at:
        $ref: '#/definitions/typeDateTime'
      updated_at:
        $ref: '#/definitions/typeDateTime'
  resourcesDiscordToken:
    type: object
    example:
      access_token: token
      expired_at: expire-time
      refresh_token: refresh-token
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      expired_at:
        type: string
  rpcAccountPatcher:
    type: object
    example:
      display_name: string
      github_id: string
      profile: string
      twitter_id: string
    properties:
      display_name:
        type: string
      profile:
        type: string
      twitter_id:
        type: string
      github_id:
        type: string
  rpcGetTagsResponse:
    type: object
    properties:
      tags:
        type: array
        items:
          type: object
          $ref: '#/definitions/tagsresourcesTag'
  rpcPostTokenResponse:
    type: object
    properties:
      expired_at:
        type: string
      refresh_token:
        type: string
      access_token:
        type: string
  tagsresourcesTag:
    type: object
    example:
      color: '#000000'
      id: "1"
      name: tag1
    properties:
      id:
        type: string
      name:
        type: string
      color:
        type: string
  typeDateTime:
    type: object
    properties:
      year:
        type: integer
        format: int32
        description: |-
          Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
          datetime without a year.
      month:
        type: integer
        format: int32
        description: Required. Month of year. Must be from 1 to 12.
      day:
        type: integer
        format: int32
        description: |-
          Required. Day of month. Must be from 1 to 31 and valid for the year and
          month.
      hours:
        type: integer
        format: int32
        description: |-
          Required. Hours of day in 24 hour format. Should be from 0 to 23. An API
          may choose to allow the value "24:00:00" for scenarios like business
          closing time.
      minutes:
        type: integer
        format: int32
        description: Required. Minutes of hour of day. Must be from 0 to 59.
      seconds:
        type: integer
        format: int32
        description: |-
          Required. Seconds of minutes of the time. Must normally be from 0 to 59. An
          API may allow the value 60 if it allows leap-seconds.
      nanos:
        type: integer
        format: int32
        description: |-
          Required. Fractions of seconds in nanoseconds. Must be from 0 to
          999,999,999.
      utc_offset:
        type: string
        description: |-
          UTC offset. Must be whole seconds, between -18 hours and +18 hours.
          For example, a UTC offset of -4:00 would be represented as
          { seconds: -14400 }.
      time_zone:
        $ref: '#/definitions/typeTimeZone'
        description: Time zone.
    description: |-
      Represents civil time (or occasionally physical time).

      This type can represent a civil time in one of a few possible ways:

       * When utc_offset is set and time_zone is unset: a civil time on a calendar
         day with a particular offset from UTC.
       * When time_zone is set and utc_offset is unset: a civil time on a calendar
         day in a particular time zone.
       * When neither time_zone nor utc_offset is set: a civil time on a calendar
         day in local time.

      The date is relative to the Proleptic Gregorian Calendar.

      If year is 0, the DateTime is considered not to have a specific year. month
      and day must have valid, non-zero values.

      This type may also be used to represent a physical time if all the date and
      time fields are set and either case of the `time_offset` oneof is set.
      Consider using `Timestamp` message for physical time instead. If your use
      case also would like to store the user's timezone, that can be done in
      another field.

      This type is more flexible than some applications may want. Make sure to
      document and validate your application's limitations.
  typeTimeZone:
    type: object
    properties:
      id:
        type: string
        description: IANA Time Zone Database time zone, e.g. "America/New_York".
      version:
        type: string
        description: Optional. IANA Time Zone Database version number, e.g. "2019a".
    description: |-
      Represents a time zone from the
      [IANA Time Zone Database](https://www.iana.org/time-zones).
