/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AuthDiscordCallbackGetHandler = http.get('/api/v1/auth/discord/callback',() => {
  return new HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthTokenPostHandler = http.post('/api/v1/auth/token',() => {
  return new HttpResponse.json({
    expired_at:'',
    refresh_token:'emoyic',
    access_token:'emoyic',
  })
})
const ApiV1AuthDiscordGetHandler = http.get('/api/v1/auth/discord',() => {
  return new HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthSignUpPostHandler = http.post('/api/v1/auth/sign_up',() => {
  return new HttpResponse.json({
    id:'ced8594e-320f-4c52-928f-ccc826895420',
    name:'Heloise Predovic',
    display_name:'Heloise Predovic',
    avatar_url:'http://iem.com/',
    profile:'vel dolor occaecati ut et iste tempora fugit blanditiis soluta totam quibusdam asperiores ut et architecto maiores earum quo eius minima est modi sunt iste qui est dolore commodi reprehenderit omnis qui similique quia sed ut autem inventore in dolorem.',
    twitter_id:'4fc78961-650c-4fe0-aaf2-0c774aa75f38',
    github_id:'5215c9bc-1222-4a8c-ad65-0e2b42183276',
    created_at:'2021-09-01T00:00:00Z',
    updated_at:'2021-09-01T00:00:00Z',
  })
})
export const authServiceHandlers = [
  ApiV1AuthDiscordCallbackGetHandler,
  ApiV1AuthTokenPostHandler,
  ApiV1AuthDiscordGetHandler,
  ApiV1AuthSignUpPostHandler,
]
