/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AuthDiscordCallbackGetHandler = http.get('/api/v1/auth/discord/callback',() => {
  return new HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthTokenPostHandler = http.post('/api/v1/auth/token',() => {
  return new HttpResponse.json({
    expired_at:'',
    refresh_token:'dnw|kktfpit',
    access_token:'dnw|kktfpit',
  })
})
const ApiV1AuthDiscordGetHandler = http.get('/api/v1/auth/discord',() => {
  return new HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthSignUpPostHandler = http.post('/api/v1/auth/sign_up',() => {
  return new HttpResponse.json({
    id:'55e4ed18-4fae-4382-a4fd-bb145159db0b',
    name:'Darien Miller',
    display_name:'Darien Miller',
    avatar_url:'https://www.nnk.info/j-fxkra',
    profile:'recusandae a sit vel a rerum nulla vero itaque aut est necessitatibus rerum ea facilis rerum omnis omnis voluptas omnis inventore excepturi atque fugit quod aut quisquam repellendus dicta ut amet nihil impedit magni saepe quia maxime necessitatibus non cumque.',
    twitter_id:'4bde3946-e972-43d8-92c7-cb6b2ca8b90b',
    github_id:'8c7bb11d-9d80-4d8b-b98b-ffa2c1d515c4',
    created_at:'2021-09-01T00:00:00Z',
    updated_at:'2021-09-01T00:00:00Z',
  })
})
export const authServiceHandlers = [
  ApiV1AuthDiscordCallbackGetHandler,
  ApiV1AuthTokenPostHandler,
  ApiV1AuthDiscordGetHandler,
  ApiV1AuthSignUpPostHandler,
]
