/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AssetsPostHandler = http.post('/api/v1/assets',() => {
  return new HttpResponse.json({
    id:'f3f7cf69-e768-409c-b939-50d522641d63',
  })
})
const ApiV1AssetsIdDeleteHandler = http.delete('/api/v1/assets/{id}',() => {
  return new HttpResponse.json({
    status:'ok',
  })
})
export const assetsServiceHandlers = [
  ApiV1AssetsPostHandler,
  ApiV1AssetsIdDeleteHandler,
]
