/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1TagsGetHandler = http.get('/api/v1/tags',() => {
  return new HttpResponse.json({
    tags:[
    {
    id:'99364ce4-5bfb-4826-97c3-0b88c4ff2bf5',
    name:'Darien Miller',
    color:'#6BFAB2',
    },
    ],
  })
})
const ApiV1TagsPostHandler = http.post('/api/v1/tags',() => {
  return new HttpResponse.json({
    id:'8644eed3-20be-46d6-818e-d483ea76ea3e',
    name:'Darien Miller',
    color:'#6BFAB2',
  })
})
const ApiV1TagsTagIdGetHandler = http.get('/api/v1/tags/{tag_id}',() => {
  return new HttpResponse.json({
    id:'bb825d93-3432-47b9-8101-c812d8c51dd4',
    name:'Darien Miller',
    color:'#6BFAB2',
  })
})
const ApiV1TagsTagIdPutHandler = http.put('/api/v1/tags/{tag_id}',() => {
  return new HttpResponse.json({
    id:'60ece3a5-0c6c-4591-a08b-90e4823e1822',
    name:'Darien Miller',
    color:'#6BFAB2',
  })
})
const ApiV1TagsTagIdDeleteHandler = http.delete('/api/v1/tags/{tag_id}',() => {
  return new HttpResponse.json({
    message:'',
  })
})
export const tagsServiceHandlers = [
  ApiV1TagsGetHandler,
  ApiV1TagsPostHandler,
  ApiV1TagsTagIdGetHandler,
  ApiV1TagsTagIdPutHandler,
  ApiV1TagsTagIdDeleteHandler,
]
