name: rebase and rebuild openapi

on:
  workflow_dispatch:

jobs:
  rebase_and_rebuild_openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Rebase
        run: git rebase main
      - name: Rebuild OpenAPI
        run: |
          make build
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<email@example.com>"
          git add .
          git commit -m "Rebuild OpenAPI"
          git push
